name: Capitalism
version: '${project.version}'
main: org.capitalism.Capitalism
api-version: '1.20'
commands:
  start:
    description: "Start the game"
  join:
    description: "Join the game"
  shop:
    description: "Spawn shop"
  chest:
    description: "Spawn chest"
